
version: '2.2'

services:  
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:ro 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-net

  nginx-proxy-acme:
    environment:
      - DEFAULT_EMAIL=development@scottrassbach.net
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /acme:/etc/acme.sh
    networks:
      - nginx-net
  
  friary.johannite.tech:
    environment:
        - LETSENCRYPT_HOST=friary.johannite.tech
        - LETSENCRYPT_EMAIL=development@scottrassbach.net
        - VIRTUAL_HOST=friary.johannite.tech
        - VIRTUAL_PORT=8081
        - KEYCLOAK_ADMIN=tandu
        - KEYCLOAK_ADMIN_PASSWORD=deusvult1972
        - KC_PROXY_HEADERS=xforwarded
        - KC_HTTP_ENABLED=true
        - KC_PROXY=edge
        - KC_HOSTNAME_STRICT=false
    container_name: friary.johannite.tech
    restart: always
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --proxy-headers xforwarded
    expose:
      - 80
      - 443
      - 8081
    ports:
      - '8081:8080'
    networks:
      - nginx-net

  api.johannite.tech:
    environment:
      - LETSENCRYPT_HOST=api.johannite.tech
      - LETSENCRYPT_EMAIL=development@scottrassbach.net
      - VIRTUAL_HOST=api.johannite.tech
      - VIRTUAL_PORT=8080
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: api.johannite.tech
    restart: always
    image: srassbach/johannitechurch:latest
    ports:
      - '8080:8080'
    expose: 
      - 80
      - 443
      - 8080
    networks:
      - nginx-net
  
  office.johannite.tech:
    environment:
      - LETSENCRYPT_HOST=office.johannite.tech
      - LETSENCRYPT_EMAIL=development@scottrassbach.net
      - VIRTUAL_HOST=office.johannite.tech
      - VIRTUAL_PORT=80
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    container_name: office.johannite.tech
    image: srassbach/johannite_liturgies_ui:latest
    expose:
      - 80
      - 443
    networks:
      - nginx-net

  www.johannite.tech:
    environment:
      - LETSENCRYPT_HOST=www.johannite.tech
      - LETSENCRYPT_EMAIL=development@scottrassbach.net
      - VIRTUAL_HOST=www.johannite.tech
      - VIRTUAL_POST=80
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    container_name: www.johannite.tech
    image: srassbach/johannitelanding:latest
    expose:
      - 80
    networks:
      - nginx-net

  agent:
    container_name: Portainer_agent
    restart: always
    image: portainer/agent
    environment:
      - VIRTUAL_HOST=portainer.johannite.tech
      - VIRTUAL_PORT=9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - '9001:9001'
    expose:
      - 9001
    networks:
      - nginx-net
volumes:
  certs:

networks:  
  nginx-net:
    external:
      name: nginx-net
